# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fabio Luciani Immunogenomics lab
email: luciani@unsw.edu.au
description: > # this means to ignore newlines until "baseurl:"
  The website of Fabio Luciani. UNSW Sydney.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabioitaus.github.io" # the base hostname & protocol for your site
twitter_username: FabioItaus
github_username:  fabioitaus

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/news/:num/"

#gems: [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  
